SELECT *  FROM PRODUCTOS WHERE ID=(SELECT ID_PRODUCTO FROM (SELECT  MIN(CONT) AS MIN, ID_PRODUCTO, ROW_NUMBER() OVER (ORDER BY MIN(CONT)) AS RN FROM (SELECT ID_PRODUCTO, SUM(CANTIDAD) AS CONT FROM PRODUCTO_COMPRA WHERE ID_COMPRA IN (SELECT ID FROM COMPRA WHERE FECHA >= '01/01/2018' AND FECHA <= '31/12/2018') GROUP BY ID_PRODUCTO)GROUP BY ID_PRODUCTO) WHERE RN = 1);

SELECT *  FROM PRODUCTOS WHERE ID=(SELECT ID_PRODUCTO FROM (SELECT  MAX(CONT) AS MIN, ID_PRODUCTO, ROW_NUMBER() OVER (ORDER BY MIN(CONT) DESC) AS RN FROM (SELECT ID_PRODUCTO, SUM(CANTIDAD) AS CONT FROM PRODUCTO_COMPRA WHERE ID_COMPRA IN (SELECT ID FROM COMPRA WHERE FECHA >= '01/01/2018' AND FECHA <= '31/12/2018') GROUP BY ID_PRODUCTO)GROUP BY ID_PRODUCTO) WHERE RN = 1);


SELECT PROVEEDOR.* FROM PROVEEDOR ,(SELECT ID_PROVEEDOR, SUM (VOL), ROW_NUMBER() OVER (ORDER BY SUM(VOL)) AS RN FROM ORDEN_DE_COMPRA oc ,(SELECT SUM(VOLUMEN) AS VOL, ID_ORDEN_DE_COMPRA FROM ORDEN_DE_COMPRA_PRODUCTO GROUP BY ID_ORDEN_DE_COMPRA) t WHERE OC.ID = t.ID_ORDEN_DE_COMPRA AND oc.FECHA_ENTREGA >= '01/01/2018' AND oc.FECHA_ENTREGA <= '31/12/2018' GROUP BY oc.ID_PROVEEDOR) x WHERE x.RN = 1 AND PROVEEDOR.NIT = x.ID_PROVEEDOR;

SELECT PROVEEDOR.* FROM PROVEEDOR ,(SELECT ID_PROVEEDOR, SUM (VOL), ROW_NUMBER() OVER (ORDER BY SUM(VOL) DESC) AS RN FROM ORDEN_DE_COMPRA oc ,(SELECT SUM(VOLUMEN) AS VOL, ID_ORDEN_DE_COMPRA FROM ORDEN_DE_COMPRA_PRODUCTO GROUP BY ID_ORDEN_DE_COMPRA) t WHERE OC.ID = t.ID_ORDEN_DE_COMPRA AND oc.FECHA_ENTREGA >= '01/01/2018' AND oc.FECHA_ENTREGA <= '31/01/2018' GROUP BY oc.ID_PROVEEDOR) x WHERE x.RN = 1 AND PROVEEDOR.NIT = x.ID_PROVEEDOR;


