SELECT PESOACTUAL/CAPACIDAD_PESO AS INDICE, ID AS ID 
FROM (SELECT SUM(PESO_EMPAQUE) AS PESOACTUAL , ID_BODEGA AS ID1 
    FROM BODEGA_PRODUCTO JOIN PRODUCTOS ON
    ID = ID_PRODUCTO GROUP BY ID_BODEGA)f 
    JOIN BODEGA ON ID1 = ID ;