(SELECT MONTHS_BETWEEN(LAST_DAY(ADD_MONTHS(SYSDATE,-1)), TO_DATE('01/01/2018','DD/MM/YYYY')) AS MESES FROM DUAL);


SELECT ID_CLIENTE as id
FROM(SELECT ID_CLIENTE, COUNT(ID_CLIENTE) as CUNT
FROM COMPRA
WHERE FECHA <= LAST_DAY(ADD_MONTHS(sysdate,-10)) AND FECHA > LAST_DAY(ADD_MONTHS(sysdate,-(1+10))) AND ID_SUCURSAL = 1
GROUP BY ID_CLIENTE
ORDER BY ID_CLIENTE)
WHERE CUNT >=2

